CREATE TABLE IMPORTED_FILES (
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL
);

CREATE UNIQUE INDEX IMPORTED_FILES_NAME_IDX ON IMPORTED_FILES(NAME);

CREATE TABLE CUSTOMERS (
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(45) NOT NULL,
    EXTERNAL_ID_FROM_IMPORTED_FILE INT NULL,
    IMPORTED_FILE_ID INT NULL,

    FOREIGN KEY (IMPORTED_FILE_ID) REFERENCES IMPORTED_FILES(ID)
);

CREATE UNIQUE INDEX CUSTOMERS_EXTERNAL_ID_FROM_IMPORTED_FILE_IMPORTED_FILE_ID_IDX ON CUSTOMERS(EXTERNAL_ID_FROM_IMPORTED_FILE, IMPORTED_FILE_ID);

CREATE TABLE ORDERS (
    ID SERIAL PRIMARY KEY,
    "date" DATE NOT NULL,
    CUSTOMER_ID INT NOT NULL,
    EXTERNAL_ID_FROM_IMPORTED_FILE INT NULL,
    IMPORTED_FILE_ID INT NULL,

    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(ID),
    FOREIGN KEY (IMPORTED_FILE_ID) REFERENCES IMPORTED_FILES(ID)
);

CREATE INDEX ORDERS_CUSTOMER_ID_IDX ON ORDERS(CUSTOMER_ID);
CREATE INDEX ORDERS_DATE_IDX ON ORDERS("date");
CREATE UNIQUE INDEX ORDERS_EXTERNAL_ID_FROM_IMPORTED_FILE_IMPORTED_FILE_ID_IDX ON ORDERS(EXTERNAL_ID_FROM_IMPORTED_FILE, IMPORTED_FILE_ID);

CREATE TABLE PRODUCTS (
    ID SERIAL PRIMARY KEY,
    EXTERNAL_ID_FROM_IMPORTED_FILE INT NULL,
    IMPORTED_FILE_ID INT NULL
);

CREATE UNIQUE INDEX PRODUCTS_EXTERNAL_ID_FROM_IMPORTED_FILE_IMPORTED_FILE_ID_IDX ON PRODUCTS(EXTERNAL_ID_FROM_IMPORTED_FILE, IMPORTED_FILE_ID);

CREATE TABLE ORDERS_PRODUCTS (
    ID SERIAL PRIMARY KEY,
    ORDER_ID INT NOT NULL,
    PRODUCT_ID INT NOT NULL,
    VALUE NUMERIC NOT NULL,

    FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ID),
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(ID)
);

CREATE INDEX ORDERS_PRODUCTS_ORDER_ID_IDX ON ORDERS_PRODUCTS(ORDER_ID);
CREATE INDEX ORDERS_PRODUCTS_PRODUCT_ID_IDX ON ORDERS_PRODUCTS(PRODUCT_ID);